services:
  postgres:
    image: postgres:14-alpine
    container_name: minijira-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: minijira-backend:current
    container_name: minijira-backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@minijira-postgres:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_ENV: production
      CORS_ORIGINS: https://51.20.4.65
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "./wait_for_db.sh && flask db upgrade && python seed.py && python run.py"

  frontend:
    image: minijira-frontend:current
    container_name: minijira-frontend

  nginx:
    image: minijira-nginx:current
    container_name: minijira-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/minijira/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres-data: