apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: minijira
type: Opaque
stringData:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
  DATABASE_URL: "${DATABASE_URL}"
  SECRET_KEY: "${SECRET_KEY}"
  FLASK_ENV: "${FLASK_ENV}"
  CORS_ORIGINS: "${CORS_ORIGINS}"
  VITE_API_URL: "${VITE_API_URL}"